#AndroidIDE: enforce UTF-8 & locale for Gradle daemon
#Wed Jun 10 01:56:14 GMT 2026
systemProp.user.language=en
systemProp.user.country=US
androidPluginVersion=8.13.0
systemProp.sun.jnu.encoding=UTF-8
org.gradle.daemon=true
systemProp.file.encoding=UTF-8
org.gradle.jvmargs=-Xms512M -Xmx1G -XX\:MaxMetaspaceSize\=1G -Dfile.encoding\=UTF-8 -Dsun.jnu.encoding\=UTF-8 -Duser.language\=en -Duser.country\=US
org.gradle.configureondemand=true
android.useAndroidX=true
gdxVersion=1.14.0
